<?php

$this->headTitle('Occupi / Show Currency Occupancy');

$this->mainMenu()->setActiveItemId('occupi/showcurrentoccupancy');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Occupi'=>$this->url('occupi'),
    'Show Currency Occupancy'=>$this->url('occupi/showcurrentoccupancy'),
]);

?>

<h1>Show Currency Occupancy</h1>

<script>
    jQuery(document).ready(function($){
        var i = setInterval(function(){
            $.ajax({
                type: "POST",
                url : "<?php echo SITE_URL_SSL;?>occupi/showcurrentoccupancy/getRealTimeData",
                //data : $("#mvl_main_new_user_login_form_data").serialize(),
                success: function(response){
                    $('#modal-occupi_test-result').html(response);
                }
            });
        },1000)


    });
</script>


<div id="occupi_test"></div>




