<?php

$this->headTitle('Occupi / Show Currency Occupancy');

$this->mainMenu()->setActiveItemId('occupi/showcurrentoccupancy');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Occupi'=>$this->url('occupi'),
    'Show Currency Occupancy'=>$this->url('occupi/showcurrentoccupancy'),
]);

?>

<h1 id="occupi_header_name">Show Currency Occupancy</h1>

<script>

   // jQuery(document).ready(function($){


        var i = setInterval(function(){
            $.ajax({
                type: "GET",
                url : "http://occupi.yottatrend.com/occupi/showcurrentoccupancy/getRealTimeData",
                //data : $("#mvl_main_new_user_login_form_data").serialize(),
                success: function(response){
                    $('#occupi_data_block').html(response);
                   // for (var i = 0; i < response.length; i++) {
                        // response[i] can be used to get each value
                      //  var sensor_data = JSON.parse(response[i]['sensor_data']);

                   // }

                }
            });
        },350);



    //});
</script>


<div id="occupi_data_block"></div>



