<?php

$this->headTitle('Occupi / Show Currency Occupancy');

$this->mainMenu()->setActiveItemId('occupi/showcurrentoccupancy');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Occupi'=>$this->url('occupi'),
    'Show Currency Occupancy'=>$this->url('occupi/showcurrentoccupancy'),
]);

?>

<h1 id="occupi_header_name">Show Currency Occupancy</h1>

<script>

   // jQuery(document).ready(function($){


        var i = setInterval(function(){
            $.ajax({
                type: "GET",
                url : "http://occupi.yottatrend.com/occupi/showcurrentoccupancy/getRealTimeData",
                //data : $("#mvl_main_new_user_login_form_data").serialize(),
                success: function(response){
                    $('#occupi_data_block_heat_map').html(response);
                   // for (var i = 0; i < response.length; i++) {
                        // response[i] can be used to get each value
                      //  var sensor_data = JSON.parse(response[i]['sensor_data']);

                   // }

                }
            });
        },520);

   var ii = setInterval(function(){
       $.ajax({
           type: "GET",
           url : "http://occupi.yottatrend.com/occupi/showcurrentoccupancy/getRealTimeDataDoor",
           //data : $("#mvl_main_new_user_login_form_data").serialize(),
           success: function(response){
               $('#occupi_data_block_door').html(response);
               // for (var i = 0; i < response.length; i++) {
               // response[i] can be used to get each value
               //  var sensor_data = JSON.parse(response[i]['sensor_data']);

               // }

           }
       });
   },480);

   var iii = setInterval(function(){
       $.ajax({
           type: "GET",
           url : "http://occupi.yottatrend.com/occupi/showcurrentoccupancy/getRealTimeDataDoorCount",
           //data : $("#mvl_main_new_user_login_form_data").serialize(),
           success: function(response){
               $('#occupi_data_block_door_cnt').html(response);
               // for (var i = 0; i < response.length; i++) {
               // response[i] can be used to get each value
               //  var sensor_data = JSON.parse(response[i]['sensor_data']);

               // }

           }
       });
   },500);

    //});
</script>


<div>
    <div>
    <div><h3 >Real-Time Heat Map</h3></div>
    <div id="occupi_data_block_heat_map"></div>
    </div>
    <div style="display: block; width: 100%">
    <div style="display: inline-block; width: 49% ;     vertical-align: top;">
        <div><h3 >Door Sensor</h3></div>
        <div id="occupi_data_block_door"></div>
    </div>
    <div style="display: inline-block; width: 49%;    vertical-align: top;">
        <div><h3 >Count</h3></div>
        <div id="occupi_data_block_door_cnt"></div>
    </div>
    </div>
</div>


