<?php
$this->headTitle('Social Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>
<?php
$client = new Google_Client();
$client->setAuthConfig(ROOT_PATH . '/config/client_secrets/client_secret_102leusercontent.com.json');
$client->setAccessType("offline");        // offline access
$client->setIncludeGrantedScopes(true);   // incremental auth
//$client->addScope('https://www.googleapis.com/auth/plus.login');
//$client->addScope('https://www.googleapis.com/auth/plus.me');
$client->addScope('https://www.googleapis.com/auth/userinfo.email');
$client->addScope('https://www.googleapis.com/auth/userinfo.profile');
$client->addScope('https://www.googleapis.com/auth/youtube');
$client->addScope('https://www.googleapis.com/auth/youtube.force-ssl');
$client->addScope('https://www.googleapis.com/auth/youtube.readonly');
$client->addScope('https://www.googleapis.com/auth/youtubepartner');
$client->addScope('https://www.googleapis.com/auth/youtubepartner-channel-audit');
$client->setRedirectUri(SITE_URL_SSL.'login/googleloginCallback');
$google_auth_url = $client->createAuthUrl();
//echo $auth_url;

?>
<script>
    var $j = jQuery.noConflict();
    $j(document).ready(function () {
        $j('#twitter-login-btn').click(function(){

          //  get_user_timeline_post_btn();


            $j.ajax({
                type: "POST",
                url: "<?php echo SITE_URL_SSL;?>login/twitterloginbtn",
                //     data: {clicked_state_name:clicked_state_name},
                success: function(results){
                    $j('#sociallogin_status').html(results);
                }
            });
        });

        $j('#google-signinButton').click(function() {
        //    auth2.grantOfflineAccess().then(google_signInCallback);
            window.location.replace("<?php echo $google_auth_url;?>");
        });
       // google_start();



    function google_start() {
        gapi.load('auth2', function() {
            auth2 = gapi.auth2.init({
                client_id: '1023095ogleusercontent.com',
                // Scopes to request in addition to 'profile' and 'email'
                //scope: 'additional_scope'
            });
        });
    }

    //// google sign-in callback function
    function google_signInCallback(authResult) {
        if (authResult['code']) {

           // $('#google-signinButton').attr('style', 'display: none');
            // Send the code to the server
            $j.ajax({
                type: 'POST',
                url: 'https://occupi.yottatrend.com/login/googleloginCallback',
                data: {code:authResult['code']},
                // Always include an `X-Requested-With` header in every AJAX request,
                // to protect against CSRF attacks.
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                },
              //  contentType: 'application/octet-stream; charset=utf-8',
                success: function(result) {
                    $j('#sociallogin_status').html(result);
                }


            });
        } else {
            // There was an error.
        }
    }
    });
</script>

<style>
    .social-login-page{
        margin: 8px;
    }
</style>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <div style="text-align: center;    margin-top: 20px;">
            <div id="sociallogin_status" style="text-align: center;    padding: 20px;">
            </div>

            <a class="social-login-page btn btn-block btn-social btn-facebook" href="https://www.facebook.com/v2.10/dialog/oauth?scope=public_profile,user_friends,email&client_id=121251241872143&redirect_uri=https://occupi.yottatrend.com/login/facebookloginCallback
">
                <span class="fa fa-facebook"></span> Sign in with Facebook
            </a>
            <a id="twitter-login-btn" class="social-login-page btn btn-block btn-social btn-twitter">
                <span class="fa fa-twitter"></span> Sign in with Twitter
            </a>
            <a id="google-signinButton" class="social-login-page btn btn-block btn-social btn-google">
                <span class="fa fa-google"></span> Sign in with Google
            </a>

            <a class="social-login-page btn btn-block btn-social btn-linkedin" href="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=86eu0frlfc402v&redirect_uri=https://www.yottatrend.com/login/linkedinloginCallback&state=<?php echo rand(9999,999999).time();?>&scope=r_basicprofile,r_emailaddress,w_share">
                <span class="fa fa-linkedin"></span> Sign in with Linkedin
            </a>
            <!--
            <a class="social-login-page btn btn-block btn-social btn-vimeo">
                <span class="fa fa-vimeo"></span> Sign in with Vimeo
            </a>-->
        </div>

        <div id="login-idpw-link" style="text-align: center;    margin-top: 50px;display: block;">
            <div>
            or
            </div>
            <div>
                <a href="<?php echo SITE_URL_SSL;?>login">Login using email & password</a>
            </div>
        </div>



    </div>
</div>