<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Reset Password';
 $this->headTitle($title);

 ?>
<script>
jQuery(document).ready(function($){




    $('#mvl_password_reset_btn').on('click' , function() {
    //var urlregex = new RegExp("^(http:\/\/www.|https:\/\/www.|ftp:\/\/www.|www.){1}([0-9A-Za-z]+\.)");
        if ($("#mvl_password_reset_email_box").val() == '') {
        $("#mvl_password_reset_email_box").focus();
        return false;
        }
        $('#mvl_password_reset_btn').hide();
      //  $('#createuserModal').modal('show');
        var useremail_buf = $("#mvl_password_reset_email_box").val();
        $.ajax({
        type: "POST",
        url : "<?php echo SITE_URL_SSL;?>user/userpwreset",
        data : {useremail_buf:useremail_buf},
        success: function(response){
            $("#mvl_password_reset_result_bar").html(response);
            $("#mvl_password_reset_result_bar").show();
        }
        });



    });
});
</script>

<div id="mvl_main_content">

    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <div id="mvl-password-reset-main-form-box" style="margin: 10px">


                <div id="mvl-password-reset-main" >

                    <p class="help-block"><?php echo $this->translate('Please enter your email to reset your password.') ?></p>
                    <div id="mvl_password_reset_result_bar" style="display:none"></div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">@</div>
                            <input id="mvl_password_reset_email_box" name="mvl_password_reset_email_box" class="form-control" type="email" placeholder="Enter E-Mail">
                        </div>
                    </div>

                    <button id="mvl_password_reset_btn" name="mvl_password_reset_btn" type="button" class="btn btn-primary"><?php echo $this->translate('Reset') ?></button>

                </div>
    </div>

</div>


