<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Change Password';
 $this->headTitle($title);

 ?>
<script>
jQuery(document).ready(function($){




    $('#mvl_password_change_btn').on('click' , function() {
    //var urlregex = new RegExp("^(http:\/\/www.|https:\/\/www.|ftp:\/\/www.|www.){1}([0-9A-Za-z]+\.)");
        if ($("#mvl_password_current_pw_box").val() == '') {
        $("#mvl_password_current_pw_box").focus();
        return false;
        } else if ($("#mvl_password_new_pw_box").val() == '') {
            $("#mvl_password_new_pw_box").focus();
            return false;
        } else if ($("#mvl_password_re_new_pw_box").val() == '') {
            $("#mvl_password_re_new_pw_box").focus();
            return false;
        } else if ($('#mvl_new_user_reg_validate').val() == '1') {
            $("#mvl_password_new_pw_box").focus();
            $("#mvl_password_re_new_pw_box").focus();
            return false;
        }
        $('#mvl_password_change_btn').hide();


        //  $('#createuserModal').modal('show');
        var useremail_buf = $("#mvl_password_reset_email_box").val();
        $.ajax({
        type: "POST",
        url : "<?php echo SITE_URL_SSL;?>user/userpwchange",
        data : $('#mvl-password-change-main-form').serialize(),
        success: function(response){
            $('#mvl_re_reg_pass_alert').val('');
            $('#mvl_reg_pass_alert').val('');
            $("#mvl_password_current_pw_box").val('');
            $("#mvl_password_new_pw_box").val('');
            $("#mvl_password_re_new_pw_box").val('');
            $("#mvl_password_change_result_bar").html(response);
            $("#mvl_password_change_result_bar").show();
            $('#mvl_password_change_btn').show();
        }
        });



    });
    $('#mvl_password_new_pw_box').on('keyup' , function() {
        var mvl_reg_pass = $('#mvl_password_new_pw_box').val();
        $.ajax({
            type: "POST",
            url : "<?php echo SITE_URL_SSL;?>user/regpasscheck",
            data : {mvl_reg_pass:mvl_reg_pass},
            success: function(response){
                $("#mvl_reg_pass_alert").html(response);
            }
        });
    });
    $('#mvl_password_re_new_pw_box').on('keyup' , function() {
        var mvl_reg_pass = $('#mvl_password_new_pw_box').val();
        var mvl_reg_re_password = $('#mvl_password_re_new_pw_box').val();
        $.ajax({
            type: "POST",
            url : "<?php echo SITE_URL_SSL;?>user/regpassmachcheck",
            data : {mvl_reg_re_password:mvl_reg_re_password,mvl_reg_pass:mvl_reg_pass},
            success: function(response){
                $("#mvl_re_reg_pass_alert").html(response);
            }
        });
    });
});
</script>

<div id="mvl_main_content">

    <h2><?php echo $this->escapeHtml($title); ?></h2>
    <div id="mvl-password-change-main-form-box" style="margin: 10px">

<form id="mvl-password-change-main-form">
                <div id="mvl-password-reset-main" >

                    <p class="help-block"><?php echo $this->translate('Please enter your current password and new password.') ?></p>
                    <div id="mvl_password_change_result_bar" style="display:none"></div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><?php echo $this->translate('Current Password') ?></div>
                            <input id="mvl_password_current_pw_box" name="mvl_password_current_pw_box" class="form-control" type="password" placeholder="<?php echo $this->translate('Please enter your existing password.') ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><?php echo $this->translate('New Password') ?></div>
                            <input id="mvl_password_new_pw_box" name="mvl_password_new_pw_box" class="form-control" type="password" placeholder="<?php echo $this->translate('Please enter your new password.') ?>">
                        </div>
                        <div id="mvl_reg_pass_alert"></div>

                    </div><div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"><?php echo $this->translate('Reenter New Password') ?></div>
                            <input id="mvl_password_re_new_pw_box" name="mvl_password_re_new_pw_box" class="form-control" type="password" placeholder="<?php echo $this->translate('Please re-enter your new password.') ?>">
                        </div>
                        <div id="mvl_re_reg_pass_alert"></div>
                    </div>
                    <div class="g-recaptcha" data-sitekey="6LfhGBETAAAAAHxgTox7GaO9zKWg_uv-eM7wYs3f"></div>
                    <input type="hidden" id="mvl_new_user_reg_validate" name="mvl_new_user_reg_validate" val="0">
                    <input type="hidden" id="mvl_userid" name="mvl_userid" value="<?php echo $GLOBALS['mvl_member_id'];?>">

                    <button id="mvl_password_change_btn" name="mvl_password_change_btn" type="button" class="btn btn-primary" style="margin: 8px"><?php echo $this->translate('Submit') ?></button>

                </div>
    </form>
    </div>

</div>


