<?php
$this->headTitle('Settings');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings'=>$this->url('application', ['action'=>'settings']),
            ]);
?>

<style>
    .nav-tabs>li>a{
        color: white;
    }

    </style>
<div class="col-md-12">

    <div class="row">

            <div class="panel with-nav-tabs panel-primary">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">
                        <li class="active tab-active"><a href="#tab1_my_profile" data-toggle="tab" style="">My Profile</a></li>

                        <li><a href="#tab3_API_access" data-toggle="tab" style="">API Access</a></li>
                        <!--
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#tab4default" data-toggle="tab">Default 4</a></li>
                                <li><a href="#tab5default" data-toggle="tab">Default 5</a></li>
                            </ul>
                        </li>
                        -->
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1_my_profile">
                            <table>
                            <?php
                            echo '<div class="col-md-4">E-mail : </div><div class="col-md-8">'.$current_user['user_email'].'</div>';
                            echo '<div class="col-md-4">Full Name : </div><div class="col-md-8">'.$current_user['user_fullname'].'</div>';
                            ?>
                            </table>
                        </div>

                        <div class="tab-pane fade" id="tab3_API_access">Coming Soon.....</div>

                    </div>
                </div>
            </div>


    </div>
</div>