<?php

$this->headTitle('Occupi');

$this->mainMenu()->setActiveItemId('occupi/showoccupancygraph');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
    'Occupi'=>$this->url('occupi'),
    'Show Occupancy Graph'=>$this->url('occupi/showoccupancygraph'),
            ]);

?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="http://occupi.yottatrend.com/libs/jqueryjqplot/jquery.jqplot.js"></script>
<script type="text/javascript" src="http://occupi.yottatrend.com/libs/jqueryjqplot/plugins/jqplot.json2.js"></script>
<link rel="stylesheet" type="text/css" href="http://occupi.yottatrend.com/libs/jqueryjqplot/jquery.jqplot.css" />
<h1>Show Occupancy Graph</h1>

<script>
    $(document).ready(function(){


        var i = setInterval(function(){

            var sel_range_buf = $('#sel_range').val();
            if (sel_range_buf != 0){
                $('#chart1').html('');
                var ajaxDataRenderer = function(url, plot, options) {
                    var ret = null;
                    $.ajax({
                        // have to use synchronous here, else the function
                        // will return before the data is fetched
                        async: false,
                        url: url,
                        dataType:"json",
                        success: function(data) {
                            ret = data;
                        }
                    });
                    return ret;
                };
                // alert(response);
                // The url for our json data

                var jsonurl = 'http://occupi.yottatrend.com/occupi/showoccupancygraph/getOccupancyData?sel_range='+sel_range_buf;

                // passing in the url string as the jqPlot data argument is a handy
                // shortcut for our renderer.  You could also have used the
                // "dataRendererOptions" option to pass in the url.
                var plot2 = $.jqplot('chart1', jsonurl,{
                    title: "Occupancy Graph",
                    dataRenderer: ajaxDataRenderer,
                    dataRendererOptions: {
                        unusedOptionalUrl: jsonurl
                    }
                });
            }


        },1500);

    });

</script>
<div>Current System Time : <?php echo date ("Y-m-d H:i:s", time());?></div>

<select id="sel_range">
    <option value="0">Please Select</option>
    <option value="by_date">By Date - last 30 days</option>
    <option value="by_hour">By Hour - last 24 hours </option>
    <option value="by_min">By Minute - last 360 minutes</option>
</select>

<div id="chart1" style="height: 450px;"></div>








